---
- hosts: all
  tasks:
    - name: Instalar Apache
      yum: name=httpd state=latest
    - name: Instalar samba
      yum:
        name: samba
        state: latest

    - name: iniciando servicios
      service:
        name: "{{ item }}"
        enabled: true
        state: started
      with_items:
         - httpd
         - smb

    - name: Abriendo Firewald
      firewalld:
        service: http
        permanent: true
        immediate: true
        state: enabled
    - name: copiando contenido
      copy:
        content: "Bienvenido a mi web"
        dest: /var/www/html/index.html
...
