---
- hosts: all
  vars_files:
    - vars1.yml
  tasks:
    - name: instalar {{ db_pkg }}
      yum:
        name: "{{ db_pkg }}"
        state: latest

    - name: iniciando {{ db_srv }}
      service:
        name: "{{ db_srv }}"
        state: started
        enabled: true
...
